### ISSUE TITLE
No longer on playstore 

### ISSUE THREAD

**Issue by KelvinCrag** [MarshMeadow/Komori#1]
![Screenshot_20230520-001404~2](https://github.com/MarshMeadow/Komori/assets/64832927/22c039b9-81d3-4375-a801-5f1a3b4851ce)

What [happened](https://play.google.com/store/apps/details?id=app.komori) ?

**Comment by MarshMeadow** [comment]
Yes, that is true, It was flagged for some reason, because Google thought that it was doing something wrong... but it is available, on the Offical Komori Discord, and also the Website/Github, that I made, it is coming soon with a new release version to the (Android) Google Play Store, and an official GitHub is not coming, sadly..

**Comment by MarshMeadow** [comment]
> ![Screenshot_20230520-001404~2](https://user-images.githubusercontent.com/64832927/239654052-22c039b9-81d3-4375-a801-5f1a3b4851ce.png)
> 
> What [happened](https://play.google.com/store/apps/details?id=app.komori) ?

It is back on the Play Store!

**Comment by KelvinCrag** [comment]
Thanks
